site_name: Gara Otterdog
site_url: https://zhe-w.com

theme:
  name: material
  icon:
    logo: fontawesome/solid/otter
  palette:
    primary: green
    accent: green
  features:
    - header.autohide

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: "&copy; 2025 perifural.com"
