site_name: REDACTED FOR PRIVACY
site_url: https://zhe-w.com

theme:
  name: material
  icon:
    logo: material/account-circle
  palette:
    primary: green
    accent: green

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true