[project]
site_name = "Caramel Gara"
site_url = "https://zhe-w.com"
site_author = "Caramel Gara"
copyright = "&copy; 2023-2026 Caramel Gara"

[project.theme.icon]
logo = "lucide/paw-print"

[project.theme]
favicon = "images/favicon.png"
custom_dir = "overrides"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "orange"
accent = "orange"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "orange"
accent = "orange"