[project]
site_name = "Caramel Gara"
site_url = "https://gara.perifural.com"
site_author = "Caramel Gara"
copyright = "&copy; 2019-2026 Caramel Gara"
extra_css = ["stylesheets/extra.css"]

[project.extra]
generator = false

[project.theme.icon]
logo = "lucide/paw-print"

[project.theme]
favicon = "images/favicon.png"
custom_dir = "overrides"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "orange"
accent = "orange"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "orange"
accent = "orange"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.attr_list]